### ISSUE TITLE
`totalLimit` is not honored

### ISSUE THREAD

**Issue by workmanw** [clarkbox/testswarm-browserstack#47]
I believe this to be a bug. If you see this segment of code, part of "task 2": [src/testswarm-browserstack.js#L601-L610](https://github.com/clarkbox/testswarm-browserstack/blob/846a55e3b5b7e0dc2cd96b39f31411369cfed212/src/testswarm-browserstack.js#L601-L610), you see it loops over the testswarm stats and spawns up browsers that are needed by testswarm.

Later on in "task 3" though, it effectively does the same thing ([testswarm-browserstack.js#L664-L69](https://github.com/clarkbox/testswarm-browserstack/blob/846a55e3b5b7e0dc2cd96b39f31411369cfed212/src/testswarm-browserstack.js#L664-L691)), except this time it does actually honor the `totalLimit`. 

I would be happy to submit a PR to have "task 2" check `workerTotal() < config.browserstack.totalLimit`, but I'm kind of curious why it even exists. I see the code comment that explains it's goal is to ignore the queue and try to get stuff booted. But this effectively causes `totalLimit` to be completely useless. Am I missing something?

**Comment by Krinkle** [comment]
This is intended. However, if you see that it misbehaves, I'm happy to reconsider this design.

Let me quote the full comment for context (emphasis added):

> [testswarm-browserstack.js#L589-L608](https://github.com/clarkbox/testswarm-browserstack/blob/v0.4.1/src/testswarm-browserstack.js#L589-L608):
>
> Task 2: Start workers for browsers with pending tests but 0 online clients
> and 0 workers (this last bit is important as we don't want to spawn another
> worker here if there is one queued but not in the swarm yet).
>
> **Note**: This is the only case where we **_ignore the total limit to use the 'queue'_** system of browserstack to start all browsers that are needed without question. It also bypasses priority because it is more important to get at least 1 of each online so that they can work asynchronous.
> And then, in Task 3, we'll **_fill in extra workers if possible._**

BrowserStack has a queue. Which means, you can request any number of browsers and those that cannot be started right away (because of quota limits) will remain queued until they are automatically spawned by BrowserStack when a slot becomes available (either by a worker timing out, explicit termination, the worker crashing, or otherwise).

Since we know we need each of the "needed" browsers, we request one unconditionally (if we didn't request any of those already). Most of those will likely start right away and, and if the quota is too low, others will remain in the "queue".

You can request the current workers from the BrowserStack API and observe that have a status of either "queue" or "running" (https://github.com/browserstack/api/tree/v4#getting-worker-status). Even without hitting the quota, workers may remain queued for a short time as resources get allocated internally.

Later, in Task 3, we see if we have any quota left. If true, we'll spawn up some more workers to increase concurrency and use of available resources.

I hope this makes sense :)

**Comment by workmanw** [comment]
Yes, actually it does. This behavior is definitely unexpected, but I do agree with your rationale.

I originally submitted this issue because I thought it was the source of my problem. It turns out to not be, but I left it open to have a dialog about it. 

You've more than convinced me this topic has been thought through. Thank you very much for taking the time to explain it.
